sudo: required
language: java
jdk: openjdk8

services:
  - docker

env:
  global:
  - secure: iZ+BzZYJm+va5HsNVYcH249cEfkKGCkcKnwgh7SOGvBKi7jYumtsOVu3bmQkK0gDqETI2SONn977BgYeSjNJJI0C4+DPmbhxnt9UU7LkR5oIZ1T0uk+c2M4El8KoG+CeOgCHIf7AzxhcnStvljJ9YIPo/GtWLFAzMhXg1Mek3BQfIuk9ea6JWQjzZq7YOUg4KcFzL2JWidNVpQN1RiYAQD32wnpR7EYiYMM7e/JVUK0GuGAAn+7o8besDwukz7/9Zdy9LHEzWlw3OUl74mPp+kTsZC0762GHwBi6a34i9E53eGo8dxZcWRaX/zm95CtyfHYbBKWbL/o0/ENFhttK45DR+ahkXwfxwkB+6gBXq1UoDZ9F8Ps+lC1evsL6Ze9wL9ngtN9Ice+5xRzgtol0x/Rg566vxG1Rk8HVT7dhXQS0i5H8dhW/X9HWmk6Uwi9ogwBbrW82NI2cUzjYnL7+srWKhSFrrFvFhDXw4TS2sJh72MSWVWz/MkVRG5SFUYogb8EZ3gPrfewLW5IDgSP4aTQYdd+aQJa4k/WgZEqZ3AT0yVvsGXYeZED90JX0Tgo8hxoD8j26+aS91FB+wnrhrQFFkqZqwiwzSieDJFQev3ohjNYqeru+6AWFTUUu1CKoq3yetwkw8Gq1eBh9r7vVoTa+go+xzQTJA49jpTFHl5Y=
  - secure: SOLgsm5T4/k2utRGggTiuz+cF3vIY07fFKJO6eFmJvhwZeI2OpW40FPJaGNaNelIvmef46pXfiyGaO7fkdAtFTbK9ePbjCW99rawHUofdrw3wCfLLB3bwP++lxqHyy0jo+7oM5MCCRZQ/x4FXmzLkf55hBZYxyXIhKQ0A/HQR45fZcoFonDXCzIKKEMIsVjsL5fIShrmQSLYRq8puCKYdPMOS6P+DVNVN8qo7mK1F7kmdvtSRyF5RkWPKVIAZ/+Iz4Pof+Szsp+wwSrCsnrVCfG9412wbYdWHShYaB7SnQdibMQUDC5VBUXe/7yP4AOl8YAvxO4rlWVK+yZEMafS4xL4ziw+5vFXvbLV/+q5shsFty5Nr380o9aoUS6hIxpG7hCVt6KTl3ZmBdG9ORXowD2VRMqLpavZhkNaQufip28wzO0O+bQy6mOMNxnfgUlzYQC6wNR67Ogl2r6KuizwbDeyAVEfUZlDOW3damf436iesUgCYpiUpyZf0AZ0zSXEe+QLrqmXh5EthpyzNGoakglgUt2P1nprfhTccTeRKG/2jsGOa44ySSbljNexWvsIxBp0gJ0gTUTkZFc5lWbfQnpxIW1HTNHTC5lH7QwfHmXfc1Gc7pFZ5kpKEEqdQ3Rj5kBtr9q7pIWy/DYxe1+A293ON2T9nfqSaTuhiwmiZ38=
  - secure: CMVmIthmqAakaNW6FiLCiz5GYzS1c8aVQF1JVe9YPnH6kEA7ho5MWquNxZcHNbr513Q1VrI0ZDAgKQT6uxYUoe5bQG7P+qgJyicVx1DzKPF1k0Fx0mZoZRWRKy+jXBDF4Y931ersTT8BwSdW5jK9sHMDRnOGkFn2u99lfLLePy3ee899OSofbsvuJlhj8Zpbyeji4keXeKg7ziQq8PBFW0e4UUqZtn+6CEjWgIN38B9uVtnkuWSEUkt7viddkEbJ6M87gY3lwsdGc3572veJMdKwIm3lCWSTdiRRRZkYzqafE2WAW+En8PY8LeRgt85/TkVmesvPU58IYJn5MjDshmm1eVH8d5ieY1XJH1yKoTpRV8Kp2dmNo1LH/6KEfUg5mUjvIE++5YMDr2pDJ48qe5lHXCJCDHLJC5KuII0ha3gbW8lgaCedkrXQFgGVl30ImdiOJUWZhIQQVU8GoThytEhSJDodl2jBbHuZlGnpS4C69+6UyBRYSpOPktqYNFGqO09rsaBQ8U4u0DbsHh/xQi2pB1GZ7PnkXSa5MUx0EILVgV9dOqGeffTeOt0VmIDKSBdr1NO3ti4H2A1hu/lWX3eFPnW1wLb+q86FblZTeCsgk1NEavxnbp4PvmoaFlG2hJd0ArNkiV5REvgmj+e5G1MwH7BlyNWKTGdojmd8Reg=
  - secure: cyk7S1vQhKkPd1ufSg3+HcEdjgbx0uDP12Z55E+anDN+L6h9zMBlWsGW+Rtgr5eRlxsAlrNnoT8Ve9Q8wJjUobuD9VnwYX5nPm6oqWz99sqzjXIHZwUDpp0i2m1wAlj4J/1YSF4ZSwhiUL3qpylz3YYDLUYppcONGtQBgU5/Hwtrjt6XZBQaAzNB/IpOug2IShZ0hpUjcmrbW98feSkOMWiHnSHs9w8bMLjKhWfQo7TagAch4jJc8kz8UxBEZP+Krvb+jB015bUBQfxU0WYX8skrDYRxP2nNdtiOpGuhRq7cIcDl+NJIU/50C85t4SJ6q98P3UY8P/U3x2vah+424XhjsnP5dd40PdlFDDUXk+HHL8U97RwuBGGQNKtzHPtn3UTGzQK0ZZEJrQpwoOUGcAbleDkBDEho+wNn4bRLjBPPeWOtBNGgXaMW0DoThyvdfQlkEneqI+JQjAkEDLhNgqiF8XNnjyyRB45BPAKAHVzuzIbsM44kMma05sOluMouvlrASXrsiZljiHDqfTIl/Trq57zk2ESaslX/VAR2H5OF7OdKI+avjk6uGlSkx9rqqXKnVX3x+CnJaWNxjs0VHBBmCkysqb3EqEyocsDLg0gMFce3j5BMx33bThwtfUVz/9wfs2bHelUCV+Zgpzg/q3UQUQFkfZuk365POSRcedg=
  - COMMIT=${TRAVIS_COMMIT::7}

addons:
  sonarcloud:
    organization: "kiiimmmchi"
    token:
      secure: $SONAR_TOKEN

script:
  - ./mvnw clean install -B
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=kimchitran/jblogger
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: traviscitestbykim
